name: ci-wellies-docs

# Controls when the workflow will run
on:
  push:
    branches: [ "main", "develop" ]
    paths:
        - 'docs/**'
        - '.github/workflows/ci-docs.yml'
  pull_request:
    branches: [ "main", "develop" ]
    paths:
        - 'docs/**'
        - '.github/workflows/ci-docs.yml'

jobs:
  build:
    name: build-docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: mamba-org/setup-micromamba@v1
      with:
        environment-name: wellies-docs
        environment-file: docs/environment.yml
    - name: Install deps
      shell: bash -l {0}  # required to load conda I think
      run: python -m pip install .[docs]
    - name: build docs
      shell: bash -l {0}  # required to load conda I think
      run: mkdocs build -v
