name: ci-wellies-docs

# Controls when the workflow will run
on:
  push:
    branches: [ "main", "develop" ]
    paths:
        - 'docs/**'
  pull_request:
    branches: [ "main", "develop" ]
    paths:
        - 'docs/**'

jobs:
  build:
    name: build-docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: wellies-docs
        mamba-version: "*"
        auto-update-conda: true
        environment-file: docs/environment.yml
        auto-activate-base: false
    - name: Conda check
      shell: bash -l {0}
      run: |
        conda info
        conda list
    - name: Install deps
      shell: bash -l {0}  # required to load conda I think
      run: python -m pip install .[docs]
    - name: build docs
      shell: bash -l {0}  # required to load conda I think
      run: mkdocs build -v
