name: ci-wellies-docs

# Controls when the workflow will run
on:
  push:
    branches: [ "main", "develop" ]
    paths:
        - 'docs/**'
  pull_request:
    branches: [ "main", "develop" ]
    paths:
        - 'docs/**'

jobs:
  build:
    name: build-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          environment-file: docs/environment.yml
          python-version: 3.10
          auto-activate-base: false
      - name: Conda check
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Install wellies and run tests
        shell: bash -l {0}  # required to load conda I think
        run: |
          python -m pip install .[docs]
          mkdocs build
